version: '3'

services:
  gympass-like-api-db:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gympass-like-api-db
